### PR TITLE
Replace flexsearch with fusejs

### PR DESCRIPTION
**Pull request by wenbingzhang**

### CODE REVIEW

**Comment by alex-shpak** [comment]
Hi!
Thanks for the PR, what benefit does fuse.js have over flexsearch?

**Comment by wenbingzhang** [comment]
> Hi! Thanks for the PR, what benefit does fuse.js have over flexsearch?

It offers simultaneous searches in multiple languages.

**Comment by rebron1900** [comment]
> > Hi! Thanks for the PR, what benefit does fuse.js have over flexsearch?
> 
> It offers simultaneous searches in multiple languages.

谢谢，我说怎么用flexsearch搜不起中文，换fuse.js后好了，而且感觉数据初始化速度要比flexsearch快很多

**Comment by alex-shpak** [comment]
I was not able to find good performance comparison between flexsearch and fusejs, but it seems to be solving multi-lang problem

**Pull request merged**
