### PR TITLE
no sectioning on home <title> #174

### PR DESCRIPTION
**Pull request by undergroundwires**

### CODE REVIEW

**Comment by alex-shpak** [comment]
👋 
Not sure what is most generic case. Home page might be as well one of docs pages, like in `exampleSite`: `Introduction | Hugo Book`

Maybe we should make title customisable instead?

**Comment by undergroundwires** [comment]
You're right. I checked it on more pages and there's no standard for it. Most of the homepages I see uses a title without sectioning, however many **documentation** pages uses sectioning. I'm not sure what the default behavior should be.

How can we make it customizable?

**Comment by alex-shpak** [comment]
Well, we can create `page-title` or `html-title` partial. Tho, question is: does it worth it?

**Comment by undergroundwires** [comment]
Closing this to not pollute the PR section

**Pull request closed without merging**
