### PR TITLE
🐞 Fix issues 352 & ♻ issues 362

### PR DESCRIPTION
**Pull request by vicevolf**
Solve this problem：
https://github.com/alex-shpak/hugo-book/issues/352

The Reason:
https://github.com/gohugoio/hugo/issues/8688

### CODE REVIEW

**Comment by alex-shpak** [comment]
Interesting, probably some special condition in hugo.
I will do some poking around before merging.

**Comment by volfclub** [comment]
Solve this problem：
https://github.com/alex-shpak/hugo-book/issues/362

The Reason:
https://discourse.gohugo.io/t/how-to-open-link-in-a-new-tab-with-hugo-book/33872/2?u=volfclub

The Solution:
https://discourse.gohugo.io/t/how-to-open-link-in-a-new-tab-with-hugo-book/33872/5?u=volfclub

```
layouts/shortcodes/columns.html

<div class="book-columns flex flex-wrap">
  {{ range split .Inner "<--->" }}
  <div class="flex-even markdown-inner">
    {{ . | $.Page.RenderString }}
  </div>
  {{ end }}
</div>
```

**Comment by alex-shpak** [comment]
Well, I wasn't able to reproduce case with page content not refreshing.
And in your website you can organise content as you want, so I don't see much point in changing `content` to `content.en` in exampleSite as it will be easier to understand for users who don't use multilang mode.

But please move `RenderString` change to another PR, that function was introduced in `0.62`, so now it is safe to add.

**Comment by alex-shpak** [comment]
Linked issue is good guess, but doesn't explain why that happens 🤷

**Comment by alex-shpak** [comment]
Lets see, I will check a bit more.

**Comment by volfclub** [comment]
> 
> 
> Well, I wasn't able to reproduce case with page content not refreshing.
> And in your website you can organise content as you want, so I don't see much point in changing `content` to `content.en` in exampleSite as it will be easier to understand for users who don't use multilang mode.
> 
> But please move `RenderString` change to another PR, that function was introduced in `0.62`, so now it is safe to add.

Refreshing Issue，Try this Repo `https://github.com/volfclub/fourry` - `content.zh/_index.md` .

Linked issue, Because if you need **Render Hooks**, which markdownify doesn’t currently support .

**Comment by alex-shpak** [comment]
nah, Render Hooks is fine, can be merged, just please move to separate Pull Request.

**Comment by alex-shpak** [comment]
Well, seems like fix is not coming from hugo developers,
Can you please cleanup PR to only container rename of content folder?

**Pull request closed without merging**
