### PR TITLE
feat: make SRI configurable

### PR DESCRIPTION
**Pull request by salekseev**

### CODE REVIEW

**Comment by alex-shpak** [comment]
Hi! Thank you for contribution.

Is there some issue with using resource integrity?

Params in theme follow camel case with `Book` prefix pattern, please change param name to `BookResourceIntegrity` or `BookSRI`, with default `true.

**Comment by jasikpark** [comment]
Is the problem that your CDN is minifying your JS/CSS files and so the SRI hash is changing? SRI shouldn't depend on the headers as I understand it...

**Comment by cf-sewe** [comment]
I upvote this PR.
If I generate a local static html bundle it fails to open locally.
For example I plan to distribute the static page as zip and some auditor should open locally in a browser.

The browser refuses to load css/js locally if the integrity field is specified.

**Comment by cf-sewe** [comment]
@alex-shpak is there a chance that we get this config parameter merged?

**Comment by alex-shpak** [comment]
This will be good to fix. Tho, var name in PR doesn't follow theme's convention for params naming.

Also I would like to try it locally, what params do you use to build distribution? If I just think about it it seems that a lot of URLs will be broken if you open file from filesystem.

**Comment by cf-sewe** [comment]
> Also I would like to try it locally, what params do you use to build distribution?

When I use these Hugo parameters, the HTML bundle works fine when loaded in the browser from a local filesystem:
```properties
baseURL = ''
relativeURLs  = true
uglyURLs = true
```

**Comment by alex-shpak** [comment]
I pushed https://github.com/alex-shpak/hugo-book/commit/fde10f131980a10c5c2c1a1612c7b42daf55360b.
Depending on URL of resource, if hostname is not present - SRI would not be added, that should solve it.

**Comment by cf-sewe** [comment]
> I pushed [fde10f1](https://github.com/alex-shpak/hugo-book/commit/fde10f131980a10c5c2c1a1612c7b42daf55360b).
> Depending on URL of resource, if hostname is not present - SRI would not be added, that should solve it.

Yes that works like a charm. Thanks a lot for the quick fix - I think this PR wont be needed anymore (depending on the use case of the original PR author).

**Comment by alex-shpak** [comment]
I will close PR then, please write here if issue is still unresolved.

**Pull request closed without merging**
