### PR TITLE
add Farsi with support for search RTL texts 

### PR DESCRIPTION
**Pull request by xhdix**
(tested in Persian)

### CODE REVIEW

**Comment by alex-shpak** [comment]
Hi!
I think in your case it is better to set settings per languadge in i18n file, like so
https://github.com/alex-shpak/hugo-book/blob/master/i18n/bn.yaml#L13-L14

**Comment by xhdix** [comment]
I do not know all RTL languages, but this can solve the problem radically. I followed [the Flexserach solution](https://github.com/nextapps-de/flexsearch#right-to-left-support).

So your suggestion is to create a new file for you in Persian and put the settings in it? (Therefore, other people can guess that Persian is also RTL and can copy it for their own language)

**Comment by alex-shpak** [comment]
Yes, I think it is better to do per-languadge to avoid surprises.

**Comment by xhdix** [comment]
done!

**Comment by alex-shpak** [comment]
👍  Thank you!

**Pull request merged**
