### PR TITLE
Add support for memaid and plantuml online.

### PR DESCRIPTION
**Pull request by Gowa2017**
Add config:
Params.plantuml: true
Params.plantuml_server: string
Params.mermaid : true

### CODE REVIEW

**Comment by alex-shpak** [comment]
Hi!
Thanks for the PR.

Mermaid support is already included via `shortcode`
https://github.com/alex-shpak/hugo-book/blob/master/layouts/shortcodes/mermaid.html

It has some logic to not add mermaid in every page.
Perhaps PlantUML should be solved same way. But I'm not sure if we need 2 diagram libraries 🤔

**Comment by alex-shpak** [comment]
Well, I think it is too heavy to add these libraries to every page on site when enabled, also `docs/inject/footer.html` is for users to overwrite and sohuld be empty in theme sources.

I think it is better if you keep that `footer.html` overwritten in your site sources.

**Comment by Gowa2017** [comment]
How about conditionaly import the js lib?

**Comment by alex-shpak** [comment]
Yes, that's why shortcode is there :) to add library on demand.

**Comment by salzig** [comment]
i like the Shortcode integration of mermaid, should also work with PlantUML flawlessly. Some inspiration (untested):

```
# layouts/shortcodes/plantuml.html
{{ if not (.Page.Scratch.Get "plantuml") }}
<!-- PlantUML -->
<script src="https://cdn.jsdelivr.net/gh/jmnote/plantuml-encoder@1.2.4/dist/plantuml-encoder.min.js"
    integrity="sha256-Qsk2KRBCN5qVZX7B+8+2IvQl1Aqc723qV1tBCQaVoqo=" crossorigin="anonymous"></script>
<script>
    (function () {
        const plantumlPrefix = "plantuml";
        Array.prototype.forEach.call(document.querySelectorAll("[class^=" + plantumlPrefix + "]"), function (code) {
            const image = document.createElement("IMG");
            image.loading = 'lazy'; // Lazy loading
                image.src = {{ .Site.Params.plantuml_server }} + '/plantuml/svg/' + plantumlEncoder.encode(code.innerText);
            code.parentNode.insertBefore(image, code);
            code.style.display = 'none';
        });
    })();
</script>
{{ end }}

<p class="plantuml{{ with .Get "class" }} {{ . }}{{ end }}">
  {{- .Inner -}}
</p>
```

```
{{< plantuml >}}
--- PlantUML Code here ---
{{< /plantuml >}}
```

**Comment by alex-shpak** [comment]
Yes, I think for users that want to add `PlantUML` they can just do it with sortcode or inject partials. I don't think keeping 2 libraries for charts is good idea.

**Pull request closed without merging**
