### PR TITLE
Fix resources

### PR DESCRIPTION
**Pull request by onedrawingperday**
@alex-shpak 

This PR will fix the demo on the Hugo Themes website.

It seems that you are using a slightly older version of Hugo because there was a change in the way the resources folders are generated a couple of versions back.

ref: https://github.com/gohugoio/hugoThemes/issues/761

### CODE REVIEW

**Comment by alex-shpak** [comment]
👍 Thank you.
I will update minimum required version then

**Comment by alex-shpak** [comment]
One thing tho, I update to hugo `0.59.1` (I was on hugo `0.59.0`) and generated files.
This looks not right

image

**Comment by alex-shpak** [comment]
I use `--baseURL=http://0.0.0.0:1313/theme/hugo-book` for generation.

**Comment by onedrawingperday** [comment]
>I use `--baseURL=http://0.0.0.0:1313/theme/hugo-book` for generation.

Instead of the above I recommend that you generate the resources simply by executing `hugo server` from within the `exampleSite` folder.

Your theme demo is now fixed when I test it locally and I am about to update it on the Hugo Themes website

**Pull request merged**
