### PR TITLE
Add custom_css param into a header

### PR DESCRIPTION
**Pull request by skyfox**
Enable custom CSS support via custom_css param in the params section. The idea was tentatively stolen from  https://discourse.gohugo.io/t/how-to-override-css-classes-with-hugo/3033/4

### CODE REVIEW

**Comment by alex-shpak** [comment]
Hi!
There is already an option to add custom css with `assets/_custom.scss`, would it work for you?

**Comment by skyfox** [comment]
`assets/_custom.scss` looks good to me, but when people fetch a theme they don't want to change it I believe.
I think it is great when you have a submodule and you up-to-date it from time to time with no merge-conflicts and store all your customization in your repository. The PR provides to way to customize CSS BUT don't touch the theme itself. Does it make sense?

**Comment by alex-shpak** [comment]
Sure,
The intended use of [these](https://github.com/alex-shpak/hugo-book#extra-customisation) and [these](https://github.com/alex-shpak/hugo-book#partials) is exactly what you want.

Create file `assets/_custom.scss` in your site root and add custom styles without touching theme.
Same work with `inject` partials, that is why they are left empty.

You can override also other files of theme like this if you want to tweak some of templates.
Check at `exampleSite` [here](/alex-shpak/hugo-book/tree/master/exampleSite/assets)

**Comment by alex-shpak** [comment]
Hi again!
Did you solve your problem in the end?

**Comment by skyfox** [comment]
Hi! Sorry for the delay. No, your suggestion solved my problem. Thank you!

**Pull request closed without merging**
