### PR TITLE
Allow disabling prev/next for specific pages

### PR DESCRIPTION
**Pull request by kadamski**

### CODE REVIEW

**Comment by alex-shpak** [comment]
Hi!
Thanks for PR. I will wait with it a bit until prev-next branch will be ready to merge to master.

Tho, I think param needs better name, `bookNavigationDisabled` is too vague, it might also mean disabling menu/toc for someone who don't know the details.

**Comment by kadamski** [comment]
Sure. It is just a suggestion that in you are going to go forward with this feature (which I hope so) it would be good to have such a possibility to disable this for some pages.

**Comment by halfrost** [comment]
@alex-shpak Hi, could I know when the prev-next branch will be merged to master?

**Comment by alex-shpak** [comment]
As it is not clear how to make prev/next pages work, I will close PR for now

**Pull request closed without merging**
