### PR TITLE
delete color-scheme in head-html

### PR DESCRIPTION
**Pull request by tcitry**
This is a suggestion about #387, just have a look.

### CODE REVIEW

**Comment by alex-shpak** [comment]
Hm, perhaps we should set it to light/dark theme background color?

**Comment by tcitry** [comment]
You mean `BookTheme` in config.toml ? I set it `auto`, and `preferred_color_scheme ` with giscus. so, there still have problem when I in dark mode in macOS.

image

**Comment by alex-shpak** [comment]
Perhaps
```
<meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff">
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="#343a40">
```

**Comment by tcitry** [comment]
I tried on my local, not fixed with `<meta name="color-scheme" content="light dark">` 😅

**Comment by alex-shpak** [comment]
But remove `<meta name="color-scheme" content="light dark">` and add snipped I posted.

**Comment by tcitry** [comment]
yes, it works.

**Comment by alex-shpak** [comment]
But this does not? I would expect that to work
```xml
<meta name="color-scheme" content="light dark">
<meta name="theme-color" media="(prefers-color-scheme: light)" content="#ffffff">
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="#343a40">
```

**Comment by tcitry** [comment]
No, its not work. I am confused too.

**Comment by tcitry** [comment]
Maybe it was a problem with giscus, and fixed with https://github.com/giscus/giscus/commit/15857d093d6115db81582cc56e01f2ce6c5ff18c, so this could be closed.

**Pull request closed without merging**
