### PR TITLE
Fixes #69 Make file based menus behave as expected

### LINKED ISSUE #69: File Tree menus list Sections multiple times
When the theme is configured without a `BookMenuBundle` in `config.toml` the menu that is displayed will list Section items more than once. The screen shot below shows this on the exampleSite.

menu-bug

### PR DESCRIPTION
**Pull request by twohey**
- Fixes #69
- Section headings are listed once
- Sections and normal pages sort with the same weights amongst themselves

### CODE REVIEW

**Comment by alex-shpak** [comment]
HI!
I see the point about ordering, we just need to consider how much this breaking change will affect existing sites.
I didn't understand part about section headings listed twice? Can you please show an example.

**Comment by twohey** [comment]
If you look in the picture on the bug, you will see "Sub Section" listed twice in the menu. To be more concrete if the content/docs/ directory is:

```
$ tree content/docs/
content/docs/
└── A
    ├── B
    │   ├── _index.md
    │   └── articleB.md
    ├── _index.md
    └── articleA.md

2 directories, 4 files
```

Then you will see A and B listed twice:

bad listing

**Comment by alex-shpak** [comment]
Heh, I scanned picture twice before and missed it 😄

Although, on clean repo with disabled `BookMenuBundle` I don't get duplicate.
image

So maybe it's environment or hugo version difference. Can you please share your site config, OS and hugo version?
I like ordering change  👍, just want to find root of the problem.

**Comment by twohey** [comment]
I installed hugo on macOS 10.14.6 using brew.

```
$ uname -a
Darwin paul-air.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
$ hugo version
Hugo Static Site Generator v0.57.2/extended darwin/amd64 BuildDate: unknown
```

I believe the root of the issue is that Sections are Pages. So the original iteration over Sections listed them and then the Pages iteration also listed the section.

**Comment by alex-shpak** [comment]
Okay, I have `0.56.3` installed, I will try `0.57`

**Comment by alex-shpak** [comment]
Yes, `0.57.2` create extra 10 pages, for sections.

**Comment by alex-shpak** [comment]
I will merge this one and add comment about breaking changes in new version.
Thanks!

**Pull request merged**
