### PR TITLE
Add Last modified date feature

### PR DESCRIPTION
**Pull request by nickshine**
This PR adds an optional last-modified date and link to latest commit for pages of `doc` type. Fits inline with the _Edit this page_ link. Disabled by default.

What it looks like without the _Edit this page_ feature:
last-modified3

What it looks like when enabled alongside the _Edit this page_ feature:
last-modified2

What it looks like on hover:

last-modified

### CODE REVIEW

**Comment by nickshine** [comment]
@alex-shpak Are you cool with these features or do you think its better to keep this theme pretty bare?  I plan to add in search for `doc` type, whether that is a PR here or just on my fork.

Thanks again for the slick theme!

**Comment by alex-shpak** [comment]
HI!
Good that you reminded me!

This looks good 👍 Have you tried to scale page for mobile devices? I reckon that they might not sit well on 400px screen, maybe then stack links vertically.
Otherwise I like it!

Regarding search, I was keeping page JS free so far, I think search is good to have but I would rather design search feature as optional.
And I'm open to suggestions, almost didn't think about how to implement search, I guess `lunr` is good candidate.

**Comment by nickshine** [comment]
@alex-shpak seems ok 🤷‍♂️ :
screen shot 2018-12-19 at 6 27 28 pm

**Comment by alex-shpak** [comment]
🎉

**Pull request merged**
