### PR TITLE
Add OnlyTranslated property

### PR DESCRIPTION
**Pull request by contributorpw**
Enables a drop-down menu for translations only if a translation is present.

The sample. The site bottom has three translations languages but the current page was translated only twice.

### CODE REVIEW

**Comment by alex-shpak** [comment]
Hi!
Thanks for the PR, looks good.
I keep param names prefixed with `Book` to preven possible collision with other modules. Perhaps name it `BookTranslated` or `BookTranslatedOnly`

**Comment by alex-shpak** [comment]
Just FYI, Links to other languages roots are present as there is only one place to select languages. In case of pages that are not untranslated it will be harder to switch to another language.

Anyway, I think lang. switch is up for rework and should be present somewhere on top of the page.

**Comment by contributorpw** [comment]
@alex-shpak, I see. My carelessness. I should have noticed it myself.

Renamed.

FYI I'm using global menu for show all root translations. Maybe we can add an example to the `exampleSite`?

**Comment by alex-shpak** [comment]
Sorry for delay. Looks good!

**Pull request merged**
