### PR TITLE
use relative link for languages

### PR DESCRIPTION
**Pull request by milahu**
cherrypick from https://github.com/alex-shpak/hugo-book/commit/2fd53c0584388b63a7d4a22b05df452eac4e9cbf

### CODE REVIEW

**Comment by alex-shpak** [comment]
Hello!
Does this change fix some problem?

**Comment by milahu** [comment]
1 year later...

i guess this makes it work with github pages
where `/` is not the main path

**Comment by alex-shpak** [comment]
Long time again :D
Originally I had set `.Permalink` in order to support multi-lang sites on multihost:
https://gohugo.io/content-management/multilingual/#configure-multilingual-multihost

I will check, perhaps there is a way to verify if multi-lang was configured for multihost

**Comment by alex-shpak** [comment]
I pushed a change with
`{{ cond hugo.IsMultihost .Permalink .RelPermalink }}`
so that it will switch between `Permalink` and `RelPermalink` depending on if site is multiHost
Should fix this problem

**Comment by milahu** [comment]
good enough, i guess : )

**Pull request closed without merging**
